/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedRefundsRouteImport } from './routes/_protected/refunds'
import { Route as ProtectedPaymentsRouteImport } from './routes/_protected/payments'
import { Route as ProtectedInvoicesRouteImport } from './routes/_protected/invoices'
import { Route as ProtectedCustomersRouteImport } from './routes/_protected/customers'
import { Route as ProtectedContractsRouteImport } from './routes/_protected/contracts'
import { Route as AuthTermsRouteImport } from './routes/_auth/terms'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProtectedProductsIndexRouteImport } from './routes/_protected/products/index'
import { Route as ProtectedBusinessPartnersIndexRouteImport } from './routes/_protected/business-partners/index'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'
import { Route as ProtectedBusinessPartnersNewRouteImport } from './routes/_protected/business-partners/new'
import { Route as ProtectedBusinessPartnersIdRouteImport } from './routes/_protected/business-partners/$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRefundsRoute = ProtectedRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsRoute = ProtectedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInvoicesRoute = ProtectedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersRoute = ProtectedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContractsRoute = ProtectedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthTermsRoute = AuthTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedProductsIndexRoute = ProtectedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBusinessPartnersIndexRoute =
  ProtectedBusinessPartnersIndexRouteImport.update({
    id: '/business-partners/',
    path: '/business-partners/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBusinessPartnersNewRoute =
  ProtectedBusinessPartnersNewRouteImport.update({
    id: '/business-partners/new',
    path: '/business-partners/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBusinessPartnersIdRoute =
  ProtectedBusinessPartnersIdRouteImport.update({
    id: '/business-partners/$id',
    path: '/business-partners/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/setup': typeof SetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/terms': typeof AuthTermsRoute
  '/contracts': typeof ProtectedContractsRoute
  '/customers': typeof ProtectedCustomersRoute
  '/invoices': typeof ProtectedInvoicesRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/refunds': typeof ProtectedRefundsRoute
  '/business-partners/$id': typeof ProtectedBusinessPartnersIdRoute
  '/business-partners/new': typeof ProtectedBusinessPartnersNewRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/business-partners/': typeof ProtectedBusinessPartnersIndexRoute
  '/products/': typeof ProtectedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/setup': typeof SetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/terms': typeof AuthTermsRoute
  '/contracts': typeof ProtectedContractsRoute
  '/customers': typeof ProtectedCustomersRoute
  '/invoices': typeof ProtectedInvoicesRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/refunds': typeof ProtectedRefundsRoute
  '/business-partners/$id': typeof ProtectedBusinessPartnersIdRoute
  '/business-partners/new': typeof ProtectedBusinessPartnersNewRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/business-partners': typeof ProtectedBusinessPartnersIndexRoute
  '/products': typeof ProtectedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/setup': typeof SetupRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/terms': typeof AuthTermsRoute
  '/_protected/contracts': typeof ProtectedContractsRoute
  '/_protected/customers': typeof ProtectedCustomersRoute
  '/_protected/invoices': typeof ProtectedInvoicesRoute
  '/_protected/payments': typeof ProtectedPaymentsRoute
  '/_protected/refunds': typeof ProtectedRefundsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/business-partners/$id': typeof ProtectedBusinessPartnersIdRoute
  '/_protected/business-partners/new': typeof ProtectedBusinessPartnersNewRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/business-partners/': typeof ProtectedBusinessPartnersIndexRoute
  '/_protected/products/': typeof ProtectedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/payments'
    | '/refunds'
    | '/business-partners/$id'
    | '/business-partners/new'
    | '/settings/account'
    | '/business-partners/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/payments'
    | '/refunds'
    | '/business-partners/$id'
    | '/business-partners/new'
    | '/settings/account'
    | '/business-partners'
    | '/products'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/setup'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/terms'
    | '/_protected/contracts'
    | '/_protected/customers'
    | '/_protected/invoices'
    | '/_protected/payments'
    | '/_protected/refunds'
    | '/_protected/'
    | '/_protected/business-partners/$id'
    | '/_protected/business-partners/new'
    | '/_protected/settings/account'
    | '/_protected/business-partners/'
    | '/_protected/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/refunds': {
      id: '/_protected/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof ProtectedRefundsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments': {
      id: '/_protected/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ProtectedPaymentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invoices': {
      id: '/_protected/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof ProtectedInvoicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers': {
      id: '/_protected/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedCustomersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contracts': {
      id: '/_protected/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ProtectedContractsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/terms': {
      id: '/_auth/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthTermsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/products/': {
      id: '/_protected/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProtectedProductsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/business-partners/': {
      id: '/_protected/business-partners/'
      path: '/business-partners'
      fullPath: '/business-partners/'
      preLoaderRoute: typeof ProtectedBusinessPartnersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/business-partners/new': {
      id: '/_protected/business-partners/new'
      path: '/business-partners/new'
      fullPath: '/business-partners/new'
      preLoaderRoute: typeof ProtectedBusinessPartnersNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/business-partners/$id': {
      id: '/_protected/business-partners/$id'
      path: '/business-partners/$id'
      fullPath: '/business-partners/$id'
      preLoaderRoute: typeof ProtectedBusinessPartnersIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTermsRoute: typeof AuthTermsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTermsRoute: AuthTermsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedContractsRoute: typeof ProtectedContractsRoute
  ProtectedCustomersRoute: typeof ProtectedCustomersRoute
  ProtectedInvoicesRoute: typeof ProtectedInvoicesRoute
  ProtectedPaymentsRoute: typeof ProtectedPaymentsRoute
  ProtectedRefundsRoute: typeof ProtectedRefundsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBusinessPartnersIdRoute: typeof ProtectedBusinessPartnersIdRoute
  ProtectedBusinessPartnersNewRoute: typeof ProtectedBusinessPartnersNewRoute
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedBusinessPartnersIndexRoute: typeof ProtectedBusinessPartnersIndexRoute
  ProtectedProductsIndexRoute: typeof ProtectedProductsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedContractsRoute: ProtectedContractsRoute,
  ProtectedCustomersRoute: ProtectedCustomersRoute,
  ProtectedInvoicesRoute: ProtectedInvoicesRoute,
  ProtectedPaymentsRoute: ProtectedPaymentsRoute,
  ProtectedRefundsRoute: ProtectedRefundsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBusinessPartnersIdRoute: ProtectedBusinessPartnersIdRoute,
  ProtectedBusinessPartnersNewRoute: ProtectedBusinessPartnersNewRoute,
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
  ProtectedBusinessPartnersIndexRoute: ProtectedBusinessPartnersIndexRoute,
  ProtectedProductsIndexRoute: ProtectedProductsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
