/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedRefundsRouteImport } from './routes/_protected/refunds'
import { Route as ProtectedPaymentsRouteImport } from './routes/_protected/payments'
import { Route as ProtectedInvoicesRouteImport } from './routes/_protected/invoices'
import { Route as ProtectedCustomersRouteImport } from './routes/_protected/customers'
import { Route as ProtectedContractsRouteImport } from './routes/_protected/contracts'
import { Route as ProtectedAssetsRouteImport } from './routes/_protected/assets'
import { Route as AuthTermsRouteImport } from './routes/_auth/terms'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRefundsRoute = ProtectedRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsRoute = ProtectedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInvoicesRoute = ProtectedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersRoute = ProtectedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContractsRoute = ProtectedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAssetsRoute = ProtectedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthTermsRoute = AuthTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/setup': typeof SetupRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/terms': typeof AuthTermsRoute
  '/assets': typeof ProtectedAssetsRoute
  '/contracts': typeof ProtectedContractsRoute
  '/customers': typeof ProtectedCustomersRoute
  '/invoices': typeof ProtectedInvoicesRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/refunds': typeof ProtectedRefundsRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/setup': typeof SetupRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/terms': typeof AuthTermsRoute
  '/assets': typeof ProtectedAssetsRoute
  '/contracts': typeof ProtectedContractsRoute
  '/customers': typeof ProtectedCustomersRoute
  '/invoices': typeof ProtectedInvoicesRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/refunds': typeof ProtectedRefundsRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/setup': typeof SetupRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/terms': typeof AuthTermsRoute
  '/_protected/assets': typeof ProtectedAssetsRoute
  '/_protected/contracts': typeof ProtectedContractsRoute
  '/_protected/customers': typeof ProtectedCustomersRoute
  '/_protected/invoices': typeof ProtectedInvoicesRoute
  '/_protected/payments': typeof ProtectedPaymentsRoute
  '/_protected/refunds': typeof ProtectedRefundsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/login'
    | '/register'
    | '/terms'
    | '/assets'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/payments'
    | '/refunds'
    | '/settings/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/login'
    | '/register'
    | '/terms'
    | '/assets'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/payments'
    | '/refunds'
    | '/settings/account'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/setup'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/terms'
    | '/_protected/assets'
    | '/_protected/contracts'
    | '/_protected/customers'
    | '/_protected/invoices'
    | '/_protected/payments'
    | '/_protected/refunds'
    | '/_protected/'
    | '/_protected/settings/account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/refunds': {
      id: '/_protected/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof ProtectedRefundsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments': {
      id: '/_protected/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ProtectedPaymentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invoices': {
      id: '/_protected/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof ProtectedInvoicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers': {
      id: '/_protected/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedCustomersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contracts': {
      id: '/_protected/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ProtectedContractsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/assets': {
      id: '/_protected/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof ProtectedAssetsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/terms': {
      id: '/_auth/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthTermsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthTermsRoute: typeof AuthTermsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthTermsRoute: AuthTermsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAssetsRoute: typeof ProtectedAssetsRoute
  ProtectedContractsRoute: typeof ProtectedContractsRoute
  ProtectedCustomersRoute: typeof ProtectedCustomersRoute
  ProtectedInvoicesRoute: typeof ProtectedInvoicesRoute
  ProtectedPaymentsRoute: typeof ProtectedPaymentsRoute
  ProtectedRefundsRoute: typeof ProtectedRefundsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAssetsRoute: ProtectedAssetsRoute,
  ProtectedContractsRoute: ProtectedContractsRoute,
  ProtectedCustomersRoute: ProtectedCustomersRoute,
  ProtectedInvoicesRoute: ProtectedInvoicesRoute,
  ProtectedPaymentsRoute: ProtectedPaymentsRoute,
  ProtectedRefundsRoute: ProtectedRefundsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
