/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as AuthTermsRouteImport } from './routes/_auth/terms'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProtectedTaxInvoicesIndexRouteImport } from './routes/_protected/tax-invoices/index'
import { Route as ProtectedServiceRequestsIndexRouteImport } from './routes/_protected/service-requests/index'
import { Route as ProtectedRefundsIndexRouteImport } from './routes/_protected/refunds/index'
import { Route as ProtectedQuotationsIndexRouteImport } from './routes/_protected/quotations/index'
import { Route as ProtectedProductsIndexRouteImport } from './routes/_protected/products/index'
import { Route as ProtectedPaymentsIndexRouteImport } from './routes/_protected/payments/index'
import { Route as ProtectedOrdersIndexRouteImport } from './routes/_protected/orders/index'
import { Route as ProtectedMaintenanceSchedulesIndexRouteImport } from './routes/_protected/maintenance-schedules/index'
import { Route as ProtectedInvoicesIndexRouteImport } from './routes/_protected/invoices/index'
import { Route as ProtectedCustomersIndexRouteImport } from './routes/_protected/customers/index'
import { Route as ProtectedContractsIndexRouteImport } from './routes/_protected/contracts/index'
import { Route as ProtectedBusinessPartnersIndexRouteImport } from './routes/_protected/business-partners/index'
import { Route as ProtectedAuditLogsIndexRouteImport } from './routes/_protected/audit-logs/index'
import { Route as ProtectedTaxInvoicesIdRouteImport } from './routes/_protected/tax-invoices/$id'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'
import { Route as ProtectedServiceRequestsNewRouteImport } from './routes/_protected/service-requests/new'
import { Route as ProtectedServiceRequestsIdRouteImport } from './routes/_protected/service-requests/$id'
import { Route as ProtectedRefundsNewRouteImport } from './routes/_protected/refunds/new'
import { Route as ProtectedRefundsIdRouteImport } from './routes/_protected/refunds/$id'
import { Route as ProtectedQuotationsNewRouteImport } from './routes/_protected/quotations/new'
import { Route as ProtectedQuotationsIdRouteImport } from './routes/_protected/quotations/$id'
import { Route as ProtectedProductsNewRouteImport } from './routes/_protected/products/new'
import { Route as ProtectedProductsIdRouteImport } from './routes/_protected/products/$id'
import { Route as ProtectedPaymentsNewRouteImport } from './routes/_protected/payments/new'
import { Route as ProtectedPaymentsIdRouteImport } from './routes/_protected/payments/$id'
import { Route as ProtectedOrdersNewRouteImport } from './routes/_protected/orders/new'
import { Route as ProtectedOrdersIdRouteImport } from './routes/_protected/orders/$id'
import { Route as ProtectedMaintenanceSchedulesNewRouteImport } from './routes/_protected/maintenance-schedules/new'
import { Route as ProtectedMaintenanceSchedulesIdRouteImport } from './routes/_protected/maintenance-schedules/$id'
import { Route as ProtectedInvoicesIdRouteImport } from './routes/_protected/invoices/$id'
import { Route as ProtectedCustomersNewRouteImport } from './routes/_protected/customers/new'
import { Route as ProtectedCustomersIdRouteImport } from './routes/_protected/customers/$id'
import { Route as ProtectedContractsIdRouteImport } from './routes/_protected/contracts/$id'
import { Route as ProtectedBusinessPartnersNewRouteImport } from './routes/_protected/business-partners/new'
import { Route as ProtectedBusinessPartnersIdRouteImport } from './routes/_protected/business-partners/$id'
import { Route as ProtectedSettingsMembersIndexRouteImport } from './routes/_protected/settings/members/index'
import { Route as ProtectedSettingsDepositAccountsIndexRouteImport } from './routes/_protected/settings/deposit-accounts/index'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTermsRoute = AuthTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedTaxInvoicesIndexRoute =
  ProtectedTaxInvoicesIndexRouteImport.update({
    id: '/tax-invoices/',
    path: '/tax-invoices/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedServiceRequestsIndexRoute =
  ProtectedServiceRequestsIndexRouteImport.update({
    id: '/service-requests/',
    path: '/service-requests/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedRefundsIndexRoute = ProtectedRefundsIndexRouteImport.update({
  id: '/refunds/',
  path: '/refunds/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQuotationsIndexRoute =
  ProtectedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProductsIndexRoute = ProtectedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsIndexRoute = ProtectedPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrdersIndexRoute = ProtectedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMaintenanceSchedulesIndexRoute =
  ProtectedMaintenanceSchedulesIndexRouteImport.update({
    id: '/maintenance-schedules/',
    path: '/maintenance-schedules/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInvoicesIndexRoute = ProtectedInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersIndexRoute = ProtectedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContractsIndexRoute = ProtectedContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBusinessPartnersIndexRoute =
  ProtectedBusinessPartnersIndexRouteImport.update({
    id: '/business-partners/',
    path: '/business-partners/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAuditLogsIndexRoute = ProtectedAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTaxInvoicesIdRoute = ProtectedTaxInvoicesIdRouteImport.update({
  id: '/tax-invoices/$id',
  path: '/tax-invoices/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedServiceRequestsNewRoute =
  ProtectedServiceRequestsNewRouteImport.update({
    id: '/service-requests/new',
    path: '/service-requests/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedServiceRequestsIdRoute =
  ProtectedServiceRequestsIdRouteImport.update({
    id: '/service-requests/$id',
    path: '/service-requests/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedRefundsNewRoute = ProtectedRefundsNewRouteImport.update({
  id: '/refunds/new',
  path: '/refunds/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRefundsIdRoute = ProtectedRefundsIdRouteImport.update({
  id: '/refunds/$id',
  path: '/refunds/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQuotationsNewRoute = ProtectedQuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQuotationsIdRoute = ProtectedQuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProductsNewRoute = ProtectedProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProductsIdRoute = ProtectedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsNewRoute = ProtectedPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsIdRoute = ProtectedPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrdersNewRoute = ProtectedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrdersIdRoute = ProtectedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMaintenanceSchedulesNewRoute =
  ProtectedMaintenanceSchedulesNewRouteImport.update({
    id: '/maintenance-schedules/new',
    path: '/maintenance-schedules/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMaintenanceSchedulesIdRoute =
  ProtectedMaintenanceSchedulesIdRouteImport.update({
    id: '/maintenance-schedules/$id',
    path: '/maintenance-schedules/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInvoicesIdRoute = ProtectedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersNewRoute = ProtectedCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersIdRoute = ProtectedCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContractsIdRoute = ProtectedContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBusinessPartnersNewRoute =
  ProtectedBusinessPartnersNewRouteImport.update({
    id: '/business-partners/new',
    path: '/business-partners/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBusinessPartnersIdRoute =
  ProtectedBusinessPartnersIdRouteImport.update({
    id: '/business-partners/$id',
    path: '/business-partners/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMembersIndexRoute =
  ProtectedSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsDepositAccountsIndexRoute =
  ProtectedSettingsDepositAccountsIndexRouteImport.update({
    id: '/settings/deposit-accounts/',
    path: '/settings/deposit-accounts/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/setup': typeof SetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/terms': typeof AuthTermsRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/business-partners/$id': typeof ProtectedBusinessPartnersIdRoute
  '/business-partners/new': typeof ProtectedBusinessPartnersNewRoute
  '/contracts/$id': typeof ProtectedContractsIdRoute
  '/customers/$id': typeof ProtectedCustomersIdRoute
  '/customers/new': typeof ProtectedCustomersNewRoute
  '/invoices/$id': typeof ProtectedInvoicesIdRoute
  '/maintenance-schedules/$id': typeof ProtectedMaintenanceSchedulesIdRoute
  '/maintenance-schedules/new': typeof ProtectedMaintenanceSchedulesNewRoute
  '/orders/$id': typeof ProtectedOrdersIdRoute
  '/orders/new': typeof ProtectedOrdersNewRoute
  '/payments/$id': typeof ProtectedPaymentsIdRoute
  '/payments/new': typeof ProtectedPaymentsNewRoute
  '/products/$id': typeof ProtectedProductsIdRoute
  '/products/new': typeof ProtectedProductsNewRoute
  '/quotations/$id': typeof ProtectedQuotationsIdRoute
  '/quotations/new': typeof ProtectedQuotationsNewRoute
  '/refunds/$id': typeof ProtectedRefundsIdRoute
  '/refunds/new': typeof ProtectedRefundsNewRoute
  '/service-requests/$id': typeof ProtectedServiceRequestsIdRoute
  '/service-requests/new': typeof ProtectedServiceRequestsNewRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/tax-invoices/$id': typeof ProtectedTaxInvoicesIdRoute
  '/audit-logs/': typeof ProtectedAuditLogsIndexRoute
  '/business-partners/': typeof ProtectedBusinessPartnersIndexRoute
  '/contracts/': typeof ProtectedContractsIndexRoute
  '/customers/': typeof ProtectedCustomersIndexRoute
  '/invoices/': typeof ProtectedInvoicesIndexRoute
  '/maintenance-schedules/': typeof ProtectedMaintenanceSchedulesIndexRoute
  '/orders/': typeof ProtectedOrdersIndexRoute
  '/payments/': typeof ProtectedPaymentsIndexRoute
  '/products/': typeof ProtectedProductsIndexRoute
  '/quotations/': typeof ProtectedQuotationsIndexRoute
  '/refunds/': typeof ProtectedRefundsIndexRoute
  '/service-requests/': typeof ProtectedServiceRequestsIndexRoute
  '/tax-invoices/': typeof ProtectedTaxInvoicesIndexRoute
  '/settings/members/': typeof ProtectedSettingsMembersIndexRoute
  '/settings/deposit-accounts/': typeof ProtectedSettingsDepositAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/setup': typeof SetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/terms': typeof AuthTermsRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/business-partners/$id': typeof ProtectedBusinessPartnersIdRoute
  '/business-partners/new': typeof ProtectedBusinessPartnersNewRoute
  '/contracts/$id': typeof ProtectedContractsIdRoute
  '/customers/$id': typeof ProtectedCustomersIdRoute
  '/customers/new': typeof ProtectedCustomersNewRoute
  '/invoices/$id': typeof ProtectedInvoicesIdRoute
  '/maintenance-schedules/$id': typeof ProtectedMaintenanceSchedulesIdRoute
  '/maintenance-schedules/new': typeof ProtectedMaintenanceSchedulesNewRoute
  '/orders/$id': typeof ProtectedOrdersIdRoute
  '/orders/new': typeof ProtectedOrdersNewRoute
  '/payments/$id': typeof ProtectedPaymentsIdRoute
  '/payments/new': typeof ProtectedPaymentsNewRoute
  '/products/$id': typeof ProtectedProductsIdRoute
  '/products/new': typeof ProtectedProductsNewRoute
  '/quotations/$id': typeof ProtectedQuotationsIdRoute
  '/quotations/new': typeof ProtectedQuotationsNewRoute
  '/refunds/$id': typeof ProtectedRefundsIdRoute
  '/refunds/new': typeof ProtectedRefundsNewRoute
  '/service-requests/$id': typeof ProtectedServiceRequestsIdRoute
  '/service-requests/new': typeof ProtectedServiceRequestsNewRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/tax-invoices/$id': typeof ProtectedTaxInvoicesIdRoute
  '/audit-logs': typeof ProtectedAuditLogsIndexRoute
  '/business-partners': typeof ProtectedBusinessPartnersIndexRoute
  '/contracts': typeof ProtectedContractsIndexRoute
  '/customers': typeof ProtectedCustomersIndexRoute
  '/invoices': typeof ProtectedInvoicesIndexRoute
  '/maintenance-schedules': typeof ProtectedMaintenanceSchedulesIndexRoute
  '/orders': typeof ProtectedOrdersIndexRoute
  '/payments': typeof ProtectedPaymentsIndexRoute
  '/products': typeof ProtectedProductsIndexRoute
  '/quotations': typeof ProtectedQuotationsIndexRoute
  '/refunds': typeof ProtectedRefundsIndexRoute
  '/service-requests': typeof ProtectedServiceRequestsIndexRoute
  '/tax-invoices': typeof ProtectedTaxInvoicesIndexRoute
  '/settings/members': typeof ProtectedSettingsMembersIndexRoute
  '/settings/deposit-accounts': typeof ProtectedSettingsDepositAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/setup': typeof SetupRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/terms': typeof AuthTermsRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/business-partners/$id': typeof ProtectedBusinessPartnersIdRoute
  '/_protected/business-partners/new': typeof ProtectedBusinessPartnersNewRoute
  '/_protected/contracts/$id': typeof ProtectedContractsIdRoute
  '/_protected/customers/$id': typeof ProtectedCustomersIdRoute
  '/_protected/customers/new': typeof ProtectedCustomersNewRoute
  '/_protected/invoices/$id': typeof ProtectedInvoicesIdRoute
  '/_protected/maintenance-schedules/$id': typeof ProtectedMaintenanceSchedulesIdRoute
  '/_protected/maintenance-schedules/new': typeof ProtectedMaintenanceSchedulesNewRoute
  '/_protected/orders/$id': typeof ProtectedOrdersIdRoute
  '/_protected/orders/new': typeof ProtectedOrdersNewRoute
  '/_protected/payments/$id': typeof ProtectedPaymentsIdRoute
  '/_protected/payments/new': typeof ProtectedPaymentsNewRoute
  '/_protected/products/$id': typeof ProtectedProductsIdRoute
  '/_protected/products/new': typeof ProtectedProductsNewRoute
  '/_protected/quotations/$id': typeof ProtectedQuotationsIdRoute
  '/_protected/quotations/new': typeof ProtectedQuotationsNewRoute
  '/_protected/refunds/$id': typeof ProtectedRefundsIdRoute
  '/_protected/refunds/new': typeof ProtectedRefundsNewRoute
  '/_protected/service-requests/$id': typeof ProtectedServiceRequestsIdRoute
  '/_protected/service-requests/new': typeof ProtectedServiceRequestsNewRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/tax-invoices/$id': typeof ProtectedTaxInvoicesIdRoute
  '/_protected/audit-logs/': typeof ProtectedAuditLogsIndexRoute
  '/_protected/business-partners/': typeof ProtectedBusinessPartnersIndexRoute
  '/_protected/contracts/': typeof ProtectedContractsIndexRoute
  '/_protected/customers/': typeof ProtectedCustomersIndexRoute
  '/_protected/invoices/': typeof ProtectedInvoicesIndexRoute
  '/_protected/maintenance-schedules/': typeof ProtectedMaintenanceSchedulesIndexRoute
  '/_protected/orders/': typeof ProtectedOrdersIndexRoute
  '/_protected/payments/': typeof ProtectedPaymentsIndexRoute
  '/_protected/products/': typeof ProtectedProductsIndexRoute
  '/_protected/quotations/': typeof ProtectedQuotationsIndexRoute
  '/_protected/refunds/': typeof ProtectedRefundsIndexRoute
  '/_protected/service-requests/': typeof ProtectedServiceRequestsIndexRoute
  '/_protected/tax-invoices/': typeof ProtectedTaxInvoicesIndexRoute
  '/_protected/settings/members/': typeof ProtectedSettingsMembersIndexRoute
  '/_protected/settings/deposit-accounts/': typeof ProtectedSettingsDepositAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/invitations/accept'
    | '/business-partners/$id'
    | '/business-partners/new'
    | '/contracts/$id'
    | '/customers/$id'
    | '/customers/new'
    | '/invoices/$id'
    | '/maintenance-schedules/$id'
    | '/maintenance-schedules/new'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/products/$id'
    | '/products/new'
    | '/quotations/$id'
    | '/quotations/new'
    | '/refunds/$id'
    | '/refunds/new'
    | '/service-requests/$id'
    | '/service-requests/new'
    | '/settings/account'
    | '/tax-invoices/$id'
    | '/audit-logs/'
    | '/business-partners/'
    | '/contracts/'
    | '/customers/'
    | '/invoices/'
    | '/maintenance-schedules/'
    | '/orders/'
    | '/payments/'
    | '/products/'
    | '/quotations/'
    | '/refunds/'
    | '/service-requests/'
    | '/tax-invoices/'
    | '/settings/members/'
    | '/settings/deposit-accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/invitations/accept'
    | '/business-partners/$id'
    | '/business-partners/new'
    | '/contracts/$id'
    | '/customers/$id'
    | '/customers/new'
    | '/invoices/$id'
    | '/maintenance-schedules/$id'
    | '/maintenance-schedules/new'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/products/$id'
    | '/products/new'
    | '/quotations/$id'
    | '/quotations/new'
    | '/refunds/$id'
    | '/refunds/new'
    | '/service-requests/$id'
    | '/service-requests/new'
    | '/settings/account'
    | '/tax-invoices/$id'
    | '/audit-logs'
    | '/business-partners'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/maintenance-schedules'
    | '/orders'
    | '/payments'
    | '/products'
    | '/quotations'
    | '/refunds'
    | '/service-requests'
    | '/tax-invoices'
    | '/settings/members'
    | '/settings/deposit-accounts'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/setup'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/terms'
    | '/invitations/accept'
    | '/_protected/'
    | '/_protected/business-partners/$id'
    | '/_protected/business-partners/new'
    | '/_protected/contracts/$id'
    | '/_protected/customers/$id'
    | '/_protected/customers/new'
    | '/_protected/invoices/$id'
    | '/_protected/maintenance-schedules/$id'
    | '/_protected/maintenance-schedules/new'
    | '/_protected/orders/$id'
    | '/_protected/orders/new'
    | '/_protected/payments/$id'
    | '/_protected/payments/new'
    | '/_protected/products/$id'
    | '/_protected/products/new'
    | '/_protected/quotations/$id'
    | '/_protected/quotations/new'
    | '/_protected/refunds/$id'
    | '/_protected/refunds/new'
    | '/_protected/service-requests/$id'
    | '/_protected/service-requests/new'
    | '/_protected/settings/account'
    | '/_protected/tax-invoices/$id'
    | '/_protected/audit-logs/'
    | '/_protected/business-partners/'
    | '/_protected/contracts/'
    | '/_protected/customers/'
    | '/_protected/invoices/'
    | '/_protected/maintenance-schedules/'
    | '/_protected/orders/'
    | '/_protected/payments/'
    | '/_protected/products/'
    | '/_protected/quotations/'
    | '/_protected/refunds/'
    | '/_protected/service-requests/'
    | '/_protected/tax-invoices/'
    | '/_protected/settings/members/'
    | '/_protected/settings/deposit-accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SetupRoute: typeof SetupRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/terms': {
      id: '/_auth/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthTermsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/tax-invoices/': {
      id: '/_protected/tax-invoices/'
      path: '/tax-invoices'
      fullPath: '/tax-invoices/'
      preLoaderRoute: typeof ProtectedTaxInvoicesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/service-requests/': {
      id: '/_protected/service-requests/'
      path: '/service-requests'
      fullPath: '/service-requests/'
      preLoaderRoute: typeof ProtectedServiceRequestsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/refunds/': {
      id: '/_protected/refunds/'
      path: '/refunds'
      fullPath: '/refunds/'
      preLoaderRoute: typeof ProtectedRefundsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/quotations/': {
      id: '/_protected/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof ProtectedQuotationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/products/': {
      id: '/_protected/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProtectedProductsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments/': {
      id: '/_protected/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof ProtectedPaymentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orders/': {
      id: '/_protected/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ProtectedOrdersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/maintenance-schedules/': {
      id: '/_protected/maintenance-schedules/'
      path: '/maintenance-schedules'
      fullPath: '/maintenance-schedules/'
      preLoaderRoute: typeof ProtectedMaintenanceSchedulesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invoices/': {
      id: '/_protected/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof ProtectedInvoicesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers/': {
      id: '/_protected/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof ProtectedCustomersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contracts/': {
      id: '/_protected/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ProtectedContractsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/business-partners/': {
      id: '/_protected/business-partners/'
      path: '/business-partners'
      fullPath: '/business-partners/'
      preLoaderRoute: typeof ProtectedBusinessPartnersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/audit-logs/': {
      id: '/_protected/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof ProtectedAuditLogsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tax-invoices/$id': {
      id: '/_protected/tax-invoices/$id'
      path: '/tax-invoices/$id'
      fullPath: '/tax-invoices/$id'
      preLoaderRoute: typeof ProtectedTaxInvoicesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/service-requests/new': {
      id: '/_protected/service-requests/new'
      path: '/service-requests/new'
      fullPath: '/service-requests/new'
      preLoaderRoute: typeof ProtectedServiceRequestsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/service-requests/$id': {
      id: '/_protected/service-requests/$id'
      path: '/service-requests/$id'
      fullPath: '/service-requests/$id'
      preLoaderRoute: typeof ProtectedServiceRequestsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/refunds/new': {
      id: '/_protected/refunds/new'
      path: '/refunds/new'
      fullPath: '/refunds/new'
      preLoaderRoute: typeof ProtectedRefundsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/refunds/$id': {
      id: '/_protected/refunds/$id'
      path: '/refunds/$id'
      fullPath: '/refunds/$id'
      preLoaderRoute: typeof ProtectedRefundsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/quotations/new': {
      id: '/_protected/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof ProtectedQuotationsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/quotations/$id': {
      id: '/_protected/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof ProtectedQuotationsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/products/new': {
      id: '/_protected/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProtectedProductsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/products/$id': {
      id: '/_protected/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProtectedProductsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments/new': {
      id: '/_protected/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof ProtectedPaymentsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments/$id': {
      id: '/_protected/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof ProtectedPaymentsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orders/new': {
      id: '/_protected/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof ProtectedOrdersNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orders/$id': {
      id: '/_protected/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof ProtectedOrdersIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/maintenance-schedules/new': {
      id: '/_protected/maintenance-schedules/new'
      path: '/maintenance-schedules/new'
      fullPath: '/maintenance-schedules/new'
      preLoaderRoute: typeof ProtectedMaintenanceSchedulesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/maintenance-schedules/$id': {
      id: '/_protected/maintenance-schedules/$id'
      path: '/maintenance-schedules/$id'
      fullPath: '/maintenance-schedules/$id'
      preLoaderRoute: typeof ProtectedMaintenanceSchedulesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invoices/$id': {
      id: '/_protected/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof ProtectedInvoicesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers/new': {
      id: '/_protected/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof ProtectedCustomersNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers/$id': {
      id: '/_protected/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof ProtectedCustomersIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contracts/$id': {
      id: '/_protected/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ProtectedContractsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/business-partners/new': {
      id: '/_protected/business-partners/new'
      path: '/business-partners/new'
      fullPath: '/business-partners/new'
      preLoaderRoute: typeof ProtectedBusinessPartnersNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/business-partners/$id': {
      id: '/_protected/business-partners/$id'
      path: '/business-partners/$id'
      fullPath: '/business-partners/$id'
      preLoaderRoute: typeof ProtectedBusinessPartnersIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/members/': {
      id: '/_protected/settings/members/'
      path: '/settings/members'
      fullPath: '/settings/members/'
      preLoaderRoute: typeof ProtectedSettingsMembersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/deposit-accounts/': {
      id: '/_protected/settings/deposit-accounts/'
      path: '/settings/deposit-accounts'
      fullPath: '/settings/deposit-accounts/'
      preLoaderRoute: typeof ProtectedSettingsDepositAccountsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTermsRoute: typeof AuthTermsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTermsRoute: AuthTermsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBusinessPartnersIdRoute: typeof ProtectedBusinessPartnersIdRoute
  ProtectedBusinessPartnersNewRoute: typeof ProtectedBusinessPartnersNewRoute
  ProtectedContractsIdRoute: typeof ProtectedContractsIdRoute
  ProtectedCustomersIdRoute: typeof ProtectedCustomersIdRoute
  ProtectedCustomersNewRoute: typeof ProtectedCustomersNewRoute
  ProtectedInvoicesIdRoute: typeof ProtectedInvoicesIdRoute
  ProtectedMaintenanceSchedulesIdRoute: typeof ProtectedMaintenanceSchedulesIdRoute
  ProtectedMaintenanceSchedulesNewRoute: typeof ProtectedMaintenanceSchedulesNewRoute
  ProtectedOrdersIdRoute: typeof ProtectedOrdersIdRoute
  ProtectedOrdersNewRoute: typeof ProtectedOrdersNewRoute
  ProtectedPaymentsIdRoute: typeof ProtectedPaymentsIdRoute
  ProtectedPaymentsNewRoute: typeof ProtectedPaymentsNewRoute
  ProtectedProductsIdRoute: typeof ProtectedProductsIdRoute
  ProtectedProductsNewRoute: typeof ProtectedProductsNewRoute
  ProtectedQuotationsIdRoute: typeof ProtectedQuotationsIdRoute
  ProtectedQuotationsNewRoute: typeof ProtectedQuotationsNewRoute
  ProtectedRefundsIdRoute: typeof ProtectedRefundsIdRoute
  ProtectedRefundsNewRoute: typeof ProtectedRefundsNewRoute
  ProtectedServiceRequestsIdRoute: typeof ProtectedServiceRequestsIdRoute
  ProtectedServiceRequestsNewRoute: typeof ProtectedServiceRequestsNewRoute
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedTaxInvoicesIdRoute: typeof ProtectedTaxInvoicesIdRoute
  ProtectedAuditLogsIndexRoute: typeof ProtectedAuditLogsIndexRoute
  ProtectedBusinessPartnersIndexRoute: typeof ProtectedBusinessPartnersIndexRoute
  ProtectedContractsIndexRoute: typeof ProtectedContractsIndexRoute
  ProtectedCustomersIndexRoute: typeof ProtectedCustomersIndexRoute
  ProtectedInvoicesIndexRoute: typeof ProtectedInvoicesIndexRoute
  ProtectedMaintenanceSchedulesIndexRoute: typeof ProtectedMaintenanceSchedulesIndexRoute
  ProtectedOrdersIndexRoute: typeof ProtectedOrdersIndexRoute
  ProtectedPaymentsIndexRoute: typeof ProtectedPaymentsIndexRoute
  ProtectedProductsIndexRoute: typeof ProtectedProductsIndexRoute
  ProtectedQuotationsIndexRoute: typeof ProtectedQuotationsIndexRoute
  ProtectedRefundsIndexRoute: typeof ProtectedRefundsIndexRoute
  ProtectedServiceRequestsIndexRoute: typeof ProtectedServiceRequestsIndexRoute
  ProtectedTaxInvoicesIndexRoute: typeof ProtectedTaxInvoicesIndexRoute
  ProtectedSettingsMembersIndexRoute: typeof ProtectedSettingsMembersIndexRoute
  ProtectedSettingsDepositAccountsIndexRoute: typeof ProtectedSettingsDepositAccountsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBusinessPartnersIdRoute: ProtectedBusinessPartnersIdRoute,
  ProtectedBusinessPartnersNewRoute: ProtectedBusinessPartnersNewRoute,
  ProtectedContractsIdRoute: ProtectedContractsIdRoute,
  ProtectedCustomersIdRoute: ProtectedCustomersIdRoute,
  ProtectedCustomersNewRoute: ProtectedCustomersNewRoute,
  ProtectedInvoicesIdRoute: ProtectedInvoicesIdRoute,
  ProtectedMaintenanceSchedulesIdRoute: ProtectedMaintenanceSchedulesIdRoute,
  ProtectedMaintenanceSchedulesNewRoute: ProtectedMaintenanceSchedulesNewRoute,
  ProtectedOrdersIdRoute: ProtectedOrdersIdRoute,
  ProtectedOrdersNewRoute: ProtectedOrdersNewRoute,
  ProtectedPaymentsIdRoute: ProtectedPaymentsIdRoute,
  ProtectedPaymentsNewRoute: ProtectedPaymentsNewRoute,
  ProtectedProductsIdRoute: ProtectedProductsIdRoute,
  ProtectedProductsNewRoute: ProtectedProductsNewRoute,
  ProtectedQuotationsIdRoute: ProtectedQuotationsIdRoute,
  ProtectedQuotationsNewRoute: ProtectedQuotationsNewRoute,
  ProtectedRefundsIdRoute: ProtectedRefundsIdRoute,
  ProtectedRefundsNewRoute: ProtectedRefundsNewRoute,
  ProtectedServiceRequestsIdRoute: ProtectedServiceRequestsIdRoute,
  ProtectedServiceRequestsNewRoute: ProtectedServiceRequestsNewRoute,
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
  ProtectedTaxInvoicesIdRoute: ProtectedTaxInvoicesIdRoute,
  ProtectedAuditLogsIndexRoute: ProtectedAuditLogsIndexRoute,
  ProtectedBusinessPartnersIndexRoute: ProtectedBusinessPartnersIndexRoute,
  ProtectedContractsIndexRoute: ProtectedContractsIndexRoute,
  ProtectedCustomersIndexRoute: ProtectedCustomersIndexRoute,
  ProtectedInvoicesIndexRoute: ProtectedInvoicesIndexRoute,
  ProtectedMaintenanceSchedulesIndexRoute:
    ProtectedMaintenanceSchedulesIndexRoute,
  ProtectedOrdersIndexRoute: ProtectedOrdersIndexRoute,
  ProtectedPaymentsIndexRoute: ProtectedPaymentsIndexRoute,
  ProtectedProductsIndexRoute: ProtectedProductsIndexRoute,
  ProtectedQuotationsIndexRoute: ProtectedQuotationsIndexRoute,
  ProtectedRefundsIndexRoute: ProtectedRefundsIndexRoute,
  ProtectedServiceRequestsIndexRoute: ProtectedServiceRequestsIndexRoute,
  ProtectedTaxInvoicesIndexRoute: ProtectedTaxInvoicesIndexRoute,
  ProtectedSettingsMembersIndexRoute: ProtectedSettingsMembersIndexRoute,
  ProtectedSettingsDepositAccountsIndexRoute: ProtectedSettingsDepositAccountsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  SetupRoute: SetupRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
